name: "terraform-deploy"

on:
  push:
    branches:
      - main
    # paths:
    #   - terraform/aws/vm/**  
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    defaults:
     run:
       shell: bash
       working-directory: ./terraform_ec2
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.3.0

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        # with:
        #   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   aws-region: ap-south-1

      - name: Terraform Init
        id: init
        run: |
            rm -rf .terraform
            terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="dev.tfvars"

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -var-file="dev.tfvars"
