name: Test Custom Action

on:
  workflow_dispatch:  # This allows manual triggering

permissions:
  issues: write
  contents: read

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Workflow Run URL
        id: get-url
        run: |
          echo "url=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV  

      - name: Request Manual Approval
        uses: trstringer/manual-approval@v1.9.1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}  # Use the correct syntax for the token
          approvers: Swapnil-Devops
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body: "This deployment requires your approval. Please review the details at ${{ env.url }}."
          exclude-workflow-initiator-as-approver: false

